"""Utilities for data preparation, Gaussian Process Regression, and analysis."""

from .bayesian_optimization import (
    BayesianOptimizationResult,
    BoTorchSurrogate,
    CandidateConstraint,
    MultiObjectiveBayesianOptimizationResult,
    MultiObjectiveBoTorchSurrogate,
    apply_candidate_constraints,
    fit_botorch_surrogate,
    fit_multi_objective_botorch_surrogate,
    observation_noise_variance,
    rank_discrete_candidates,
    rank_multi_objective_discrete_candidates,
    select_diverse_batch,
    suggest_multi_objective_next_experiments,
    suggest_next_experiments,
)
from .candidate_generation import (
    build_cartesian_candidate_grid,
    build_composition_candidate_grid,
    exclude_existing_candidates,
    split_candidate_features,
)
from .data_cleaning import (
    drop_columns_by_missing_fraction,
    drop_duplicate_rows,
    filter_iqr_outliers,
    impute_missing_values,
    normalize_column_names,
    replace_missing_placeholders,
)
from .data_splitting import separate_features_target, split_train_test
from .derivative_gpr import (
    DerivativeConstrainedGPRPrediction,
    DerivativeConstrainedGPRResult,
    DerivativeObservationSet,
    MonotonicDerivativeConstraint,
    combine_derivative_observations,
    fit_derivative_constrained_gpr,
)
from .estimators import MatGPRRegressor, PhysicsInformedGPRRegressor
from .experiment_logging import (
    append_closed_loop_records,
    load_closed_loop_log,
    log_bo_recommendations,
    log_observations,
    log_selected_experiments,
    summarize_closed_loop_log,
)
from .featurizers import (
    CompositionFeaturizer,
    PolymerSmilesFeaturizer,
    SmilesFeaturizer,
    StructureFeaturizer,
)
from .fingerprint_cache import FINGERPRINT_CACHE_SCHEMA_VERSION, fingerprint_cache_key
from .io_utils import load_artifact, log_experiment_result, save_artifact
from .kernels import (
    ElementFractionKernel,
    FeatureSubsetKernel,
    StructureFeatureKernel,
    TanimotoKernel,
    build_additive_kernel,
    build_element_fraction_gpr_kernel,
    build_product_kernel,
    build_structure_gpr_kernel,
    build_tanimoto_gpr_kernel,
    pairwise_composition_distance,
    pairwise_structure_distance,
    pairwise_tanimoto_similarity,
)
from .metrics import regression_metrics, train_test_regression_metrics
from .multi_objective import (
    ObjectiveSpec,
    pareto_front_mask,
    rank_multi_objective_candidates,
    scalarize_objectives,
    select_pareto_front,
)
from .noise_models import (
    FeatureNoiseModel,
    ObservationNoiseProfile,
    ReplicateNoiseModel,
    SourceNoiseModel,
    combine_noise_profiles,
    constant_noise_profile,
)
from .inorganic_fingerprints import (
    CompositionFingerprintResult,
    append_composition_fingerprints,
    append_element_fractions,
    clean_formula,
    composition_fingerprint,
    default_element_symbols,
    element_fraction_fingerprint,
    featurize_compositions,
    featurize_element_fractions,
)
from .organic_fingerprints import (
    DEFAULT_RDKIT_DESCRIPTORS,
    SmilesFingerprintResult,
    append_smiles_features,
    canonicalize_molecule_smiles,
    canonicalize_polymer_smiles,
    featurize_smiles,
    fingerprint_smiles,
)
from .optional_dependencies import (
    OPTIONAL_DEPENDENCIES,
    OptionalDependency,
    is_optional_dependency_available,
    list_optional_dependencies,
    require_optional_dependency,
)
from .structure_fingerprints import (
    DEFAULT_STRUCTURE_FEATURES,
    StructureFingerprintResult,
    append_structure_fingerprints,
    featurize_structures,
    structure_feature_names,
    structure_fingerprint,
)
from .pca import fit_pca, summarize_pca, transform_pca
from .physics_constraints import (
    AugmentedTrainingData,
    KnownLimitConstraint,
    MonotonicTrendConstraint,
    VirtualObservationSet,
    append_virtual_observations,
    combine_virtual_observations,
)
from .physics_equations import (
    R_GAS_CONSTANT_J_MOL_K,
    PhysicsEquationTemplate,
    arrhenius_rate_equation,
    arrhenius_sqrt_time_equation,
    available_physics_equation_templates,
    free_volume_exponential_equation,
    get_physics_equation_template,
    hall_petch_equation,
    list_physics_equation_templates,
    power_law_equation,
    rule_of_mixtures_equation,
)
from .preprocessing import build_preprocessor, build_scaler, identify_feature_types
from .reporting import summarize_missingness, summarize_numeric_columns
from .sklearn_gpr import (
    build_sklearn_gpr_grid_search,
    build_sklearn_gpr_kernel,
    build_sklearn_gpr_model,
)
from .target_transforms import (
    BoundedTargetTransform,
    IdentityTargetTransform,
    LogTargetTransform,
    PhysicsResidualTransform,
    StandardizedTargetTransform,
    make_target_transform,
)
from .uncertainty import (
    calibration_curve,
    gaussian_nlpd,
    interval_coverage,
    prediction_interval_bounds,
    standardized_residuals,
    uncertainty_diagnostics,
    uncertainty_error_correlation,
)
from .validation import (
    CrossValidationResult,
    LearningCurveResult,
    TrainTestValidationResult,
    cross_validate_regressor,
    evaluate_train_test_split,
    learning_curve,
)
from .visualization import (
    plot_correlation_matrix,
    plot_distribution,
    plot_learning_curve,
    plot_parity,
    plot_pca_scores,
    plot_pca_scree,
    plot_uncertainty_calibration,
    plot_uncertainty_vs_error,
)

try:
    from .gpytorch_gpr import (
        EquationMeanFunction,
        ExactGPRModel,
        GPyTorchGPRResult,
        GPyTorchPrediction,
        PhysicsInformedMean,
        fit_gpytorch_gpr,
        predict_gpytorch_gpr,
        train_gpytorch_gpr,
    )
except ImportError:
    EquationMeanFunction = None
    ExactGPRModel = None
    GPyTorchGPRResult = None
    GPyTorchPrediction = None
    PhysicsInformedMean = None
    fit_gpytorch_gpr = None
    predict_gpytorch_gpr = None
    train_gpytorch_gpr = None

__all__ = [
    "EquationMeanFunction",
    "ExactGPRModel",
    "FeatureSubsetKernel",
    "GPyTorchGPRResult",
    "GPyTorchPrediction",
    "AugmentedTrainingData",
    "BayesianOptimizationResult",
    "BoTorchSurrogate",
    "CandidateConstraint",
    "DerivativeConstrainedGPRPrediction",
    "DerivativeConstrainedGPRResult",
    "DerivativeObservationSet",
    "IdentityTargetTransform",
    "KnownLimitConstraint",
    "LogTargetTransform",
    "MatGPRRegressor",
    "MonotonicDerivativeConstraint",
    "MonotonicTrendConstraint",
    "MultiObjectiveBayesianOptimizationResult",
    "MultiObjectiveBoTorchSurrogate",
    "PhysicsInformedMean",
    "PhysicsInformedGPRRegressor",
    "PhysicsResidualTransform",
    "PhysicsEquationTemplate",
    "CompositionFingerprintResult",
    "CompositionFeaturizer",
    "CrossValidationResult",
    "DEFAULT_RDKIT_DESCRIPTORS",
    "DEFAULT_STRUCTURE_FEATURES",
    "ElementFractionKernel",
    "FINGERPRINT_CACHE_SCHEMA_VERSION",
    "FeatureNoiseModel",
    "LearningCurveResult",
    "R_GAS_CONSTANT_J_MOL_K",
    "PolymerSmilesFeaturizer",
    "ObservationNoiseProfile",
    "OPTIONAL_DEPENDENCIES",
    "OptionalDependency",
    "ObjectiveSpec",
    "ReplicateNoiseModel",
    "SmilesFingerprintResult",
    "SmilesFeaturizer",
    "SourceNoiseModel",
    "StandardizedTargetTransform",
    "StructureFeatureKernel",
    "StructureFeaturizer",
    "StructureFingerprintResult",
    "TanimotoKernel",
    "TrainTestValidationResult",
    "VirtualObservationSet",
    "append_composition_fingerprints",
    "append_element_fractions",
    "append_smiles_features",
    "append_structure_fingerprints",
    "append_closed_loop_records",
    "append_virtual_observations",
    "arrhenius_rate_equation",
    "arrhenius_sqrt_time_equation",
    "available_physics_equation_templates",
    "apply_candidate_constraints",
    "BoundedTargetTransform",
    "build_additive_kernel",
    "build_cartesian_candidate_grid",
    "build_composition_candidate_grid",
    "build_element_fraction_gpr_kernel",
    "build_product_kernel",
    "build_preprocessor",
    "build_scaler",
    "build_sklearn_gpr_grid_search",
    "build_sklearn_gpr_kernel",
    "build_sklearn_gpr_model",
    "build_structure_gpr_kernel",
    "build_tanimoto_gpr_kernel",
    "canonicalize_molecule_smiles",
    "canonicalize_polymer_smiles",
    "calibration_curve",
    "clean_formula",
    "combine_virtual_observations",
    "combine_derivative_observations",
    "combine_noise_profiles",
    "composition_fingerprint",
    "constant_noise_profile",
    "cross_validate_regressor",
    "default_element_symbols",
    "drop_columns_by_missing_fraction",
    "drop_duplicate_rows",
    "element_fraction_fingerprint",
    "evaluate_train_test_split",
    "exclude_existing_candidates",
    "featurize_compositions",
    "featurize_element_fractions",
    "featurize_smiles",
    "featurize_structures",
    "filter_iqr_outliers",
    "fit_botorch_surrogate",
    "fit_multi_objective_botorch_surrogate",
    "fingerprint_smiles",
    "fingerprint_cache_key",
    "fit_derivative_constrained_gpr",
    "fit_gpytorch_gpr",
    "fit_pca",
    "free_volume_exponential_equation",
    "gaussian_nlpd",
    "get_physics_equation_template",
    "hall_petch_equation",
    "identify_feature_types",
    "impute_missing_values",
    "interval_coverage",
    "is_optional_dependency_available",
    "load_artifact",
    "load_closed_loop_log",
    "list_optional_dependencies",
    "log_bo_recommendations",
    "log_experiment_result",
    "log_observations",
    "log_selected_experiments",
    "list_physics_equation_templates",
    "learning_curve",
    "make_target_transform",
    "normalize_column_names",
    "observation_noise_variance",
    "pairwise_composition_distance",
    "pairwise_structure_distance",
    "pairwise_tanimoto_similarity",
    "pareto_front_mask",
    "plot_correlation_matrix",
    "plot_distribution",
    "plot_learning_curve",
    "plot_parity",
    "plot_pca_scores",
    "plot_pca_scree",
    "plot_uncertainty_calibration",
    "plot_uncertainty_vs_error",
    "prediction_interval_bounds",
    "predict_gpytorch_gpr",
    "power_law_equation",
    "rank_discrete_candidates",
    "rank_multi_objective_discrete_candidates",
    "rank_multi_objective_candidates",
    "regression_metrics",
    "replace_missing_placeholders",
    "require_optional_dependency",
    "rule_of_mixtures_equation",
    "save_artifact",
    "scalarize_objectives",
    "separate_features_target",
    "select_diverse_batch",
    "select_pareto_front",
    "split_train_test",
    "split_candidate_features",
    "standardized_residuals",
    "structure_feature_names",
    "structure_fingerprint",
    "summarize_closed_loop_log",
    "summarize_missingness",
    "summarize_numeric_columns",
    "suggest_multi_objective_next_experiments",
    "suggest_next_experiments",
    "summarize_pca",
    "train_gpytorch_gpr",
    "train_test_regression_metrics",
    "transform_pca",
    "uncertainty_diagnostics",
    "uncertainty_error_correlation",
]
