"""Utilities for data preparation, Gaussian Process Regression, and analysis."""

from __future__ import annotations

from importlib import import_module
from typing import Any

from ._version import __version__

__all__ = [
    "__version__",
    "ALLOWED_SAFE_EQUATION_FUNCTIONS",
    "ALLOWED_SAFE_EQUATION_OPERATORS",
    "EquationMeanFunction",
    "ExactGPRModel",
    "ExactMultitaskGPRModel",
    "ExactSparseMultitaskGPRModel",
    "FeatureSubsetKernel",
    "GPyTorchGPRResult",
    "GPyTorchPrediction",
    "HeteroscedasticGPRPrediction",
    "HeteroscedasticGPRResult",
    "AugmentedTrainingData",
    "BayesianOptimizationResult",
    "BOCampaignState",
    "BOBenchmarkComparison",
    "BOBenchmarkResult",
    "BOBenchmarkStrategy",
    "BORecommendationAudit",
    "BoTorchSurrogate",
    "CandidateConstraint",
    "CandidateDuplicatePolicy",
    "CandidatePoolDiagnostics",
    "CandidateTrustRegion",
    "CoKrigingGPRPrediction",
    "CoKrigingGPRRegressor",
    "CoKrigingGPRResult",
    "CoKrigingTrainTestValidationResult",
    "DerivativeConstrainedGPRPrediction",
    "DerivativeConstrainedGPRResult",
    "DerivativeObservationSet",
    "IdentityTargetTransform",
    "KnownLimitConstraint",
    "LogTargetTransform",
    "MatGPRRegressor",
    "MissingValueReport",
    "MonotonicDerivativeConstraint",
    "MonotonicTrendConstraint",
    "MultiFidelityGPRPrediction",
    "MultiFidelityGPRRegressor",
    "MultiFidelityObservationData",
    "MultiObjectiveBayesianOptimizationResult",
    "MultiObjectiveBoTorchSurrogate",
    "MultitaskGPRRegressor",
    "MultitaskGPyTorchPrediction",
    "MultitaskGPyTorchResult",
    "MultitaskTrainTestValidationResult",
    "PhysicsInformedMean",
    "PhysicsInformedGPRRegressor",
    "PhysicsResidualTransform",
    "PhysicsEquationTemplate",
    "PhysicsFeatureSpec",
    "PhysicsParameterSpec",
    "CompositionFingerprintResult",
    "CompositionFeaturizer",
    "CrossValidationResult",
    "DEFAULT_RDKIT_DESCRIPTORS",
    "DEFAULT_MAGPIE_PROPERTIES",
    "DEFAULT_MAGPIE_STATISTICS",
    "DEFAULT_STRUCTURE_FEATURES",
    "DeltaMultiFidelityGPRResult",
    "ElementFractionKernel",
    "ExactTwoLevelCoKrigingGPRModel",
    "FINGERPRINT_CACHE_SCHEMA_VERSION",
    "FeatureNoiseModel",
    "LearningCurveResult",
    "MagpieCompositionFeaturizer",
    "R_GAS_CONSTANT_J_MOL_K",
    "SAFE_EQUATION_SCHEMA_VERSION",
    "PolymerSmilesFeaturizer",
    "ObservationNoiseProfile",
    "OPTIONAL_DEPENDENCIES",
    "OptionalDependency",
    "ObjectiveSpec",
    "ReplicateNoiseModel",
    "SmilesFingerprintResult",
    "SmilesFeaturizer",
    "SourceNoiseModel",
    "SparseMultitaskGPRRegressor",
    "SparseMultitaskGPyTorchResult",
    "SparseMultitaskObservationData",
    "SparseMultitaskTrainTestValidationResult",
    "StandardizedTargetTransform",
    "StructureFeatureKernel",
    "StructureFeaturizer",
    "StructureFingerprintResult",
    "SafeEquationConstant",
    "SafeEquationEvaluationResult",
    "SafeEquationMeanFunction",
    "SafeEquationMeanPreview",
    "SafeEquationParameter",
    "SafeEquationSpec",
    "SafeEquationValidationIssue",
    "SafeEquationValidationResult",
    "SafeEquationVariable",
    "TanimotoKernel",
    "TargetTransformSpec",
    "TrainTestValidationResult",
    "VirtualObservationSet",
    "append_composition_fingerprints",
    "append_element_fractions",
    "append_magpie_composition_features",
    "append_smiles_features",
    "append_structure_fingerprints",
    "append_closed_loop_records",
    "append_virtual_observations",
    "arrhenius_linear_growth_equation",
    "arrhenius_rate_equation",
    "arrhenius_sqrt_time_equation",
    "available_physics_equation_templates",
    "available_target_transform_specs",
    "apply_candidate_constraints",
    "apply_candidate_duplicate_policy",
    "apply_candidate_trust_region",
    "BoundedTargetTransform",
    "build_additive_kernel",
    "build_cartesian_candidate_grid",
    "build_composition_candidate_grid",
    "build_element_fraction_gpr_kernel",
    "build_product_kernel",
    "build_preprocessor",
    "build_safe_equation_mean_function",
    "build_scaler",
    "build_sklearn_gpr_grid_search",
    "build_sklearn_gpr_kernel",
    "build_sklearn_gpr_model",
    "build_structure_gpr_kernel",
    "build_tanimoto_gpr_kernel",
    "canonicalize_molecule_smiles",
    "canonicalize_polymer_smiles",
    "calibration_curve",
    "clean_formula",
    "combine_virtual_observations",
    "combine_derivative_observations",
    "combine_noise_profiles",
    "compare_bo_strategies",
    "composition_fingerprint",
    "constant_noise_profile",
    "cokriging_learning_curve",
    "cross_validate_regressor",
    "default_element_symbols",
    "describe_physics_equation_template",
    "describe_target_transform_spec",
    "decompose_multifidelity_prediction",
    "drop_columns_by_missing_fraction",
    "drop_duplicate_rows",
    "element_fraction_fingerprint",
    "evaluate_cokriging_train_test_split",
    "evaluate_multitask_train_test_split",
    "evaluate_sparse_multitask_train_test_split",
    "evaluate_train_test_split",
    "evaluate_safe_equation_numpy",
    "evaluate_safe_equation_torch",
    "exclude_existing_candidates",
    "featurize_compositions",
    "featurize_element_fractions",
    "featurize_magpie_compositions",
    "featurize_smiles",
    "featurize_structures",
    "filter_iqr_outliers",
    "fit_botorch_surrogate",
    "fit_cokriging_gpr",
    "fit_multi_objective_botorch_surrogate",
    "fingerprint_smiles",
    "fingerprint_cache_key",
    "fit_derivative_constrained_gpr",
    "fit_delta_multifidelity_gpr",
    "fit_gpytorch_gpr",
    "fit_heteroscedastic_gpr",
    "fit_multitask_gpytorch_gpr",
    "fit_pca",
    "fit_sparse_multitask_gpytorch_gpr",
    "free_volume_exponential_equation",
    "gaussian_nlpd",
    "get_physics_equation_template",
    "get_target_transform_spec",
    "hall_petch_equation",
    "linear_parabolic_growth_equation",
    "linear_growth_equation",
    "identify_feature_types",
    "impute_missing_values",
    "interval_coverage",
    "infer_next_bo_iteration",
    "initialize_safe_equation_torch_parameters",
    "is_optional_dependency_available",
    "json_safe_diagnostics",
    "json_safe_metrics",
    "json_safe_regression_metrics",
    "json_safe_train_test_regression_metrics",
    "json_safe_uncertainty_diagnostics",
    "load_artifact",
    "load_closed_loop_log",
    "list_optional_dependencies",
    "list_target_transform_specs",
    "log_bo_recommendations",
    "log_experiment_result",
    "log_observations",
    "log_selected_experiments",
    "list_physics_equation_templates",
    "learning_curve",
    "multifidelity_learning_curve",
    "make_materials_target_transform",
    "make_target_transform",
    "normalize_column_names",
    "observation_noise_variance",
    "pairwise_composition_distance",
    "pairwise_structure_distance",
    "pairwise_tanimoto_similarity",
    "pareto_front_mask",
    "plot_bo_benchmark_trace",
    "plot_bo_campaign_progress",
    "plot_bo_regret_trace",
    "plot_correlation_matrix",
    "plot_distribution",
    "plot_learning_curve",
    "plot_parity",
    "plot_pca_scores",
    "plot_pca_scree",
    "plot_uncertainty_calibration",
    "plot_uncertainty_vs_error",
    "prediction_interval_bounds",
    "preview_safe_equation_mean",
    "predict_gpytorch_gpr",
    "predict_multitask_gpytorch_gpr",
    "predict_sparse_multitask_gpytorch_gpr",
    "prepare_sparse_multitask_observations",
    "prepare_multifidelity_observations",
    "power_law_equation",
    "rank_discrete_candidates",
    "rank_multi_objective_discrete_candidates",
    "rank_multi_objective_candidates",
    "regression_metrics",
    "replace_missing_placeholders",
    "resume_bo_campaign",
    "require_optional_dependency",
    "rule_of_mixtures_equation",
    "safe_equation_schema_snapshot",
    "search_physics_equation_templates",
    "search_target_transform_specs",
    "save_artifact",
    "scalarize_objectives",
    "separate_features_target",
    "select_diverse_batch",
    "select_sequential_multi_objective_batch",
    "select_pareto_front",
    "simulate_bo_strategy",
    "split_train_test",
    "split_candidate_features",
    "standardized_residuals",
    "structure_feature_names",
    "structure_fingerprint",
    "summarize_bo_benchmark",
    "summarize_closed_loop_log",
    "summarize_missingness",
    "summarize_multifidelity_components",
    "summarize_multitask_predictions",
    "summarize_numeric_columns",
    "summarize_physics_equation_templates",
    "summarize_sparse_multitask_predictions",
    "summarize_target_transform_specs",
    "suggest_multi_objective_next_experiments",
    "suggest_next_experiments",
    "summarize_bo_recommendation_audit",
    "summarize_candidate_category_coverage",
    "summarize_candidate_duplicates",
    "summarize_candidate_feature_coverage",
    "summarize_candidate_pool",
    "summarize_pca",
    "train_gpytorch_gpr",
    "train_multitask_gpytorch_gpr",
    "train_sparse_multitask_gpytorch_gpr",
    "train_test_regression_metrics",
    "transform_pca",
    "uncertainty_diagnostics",
    "uncertainty_error_correlation",
    "validate_safe_equation_spec",
]

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "ALLOWED_SAFE_EQUATION_FUNCTIONS": (".safe_equations", "ALLOWED_SAFE_EQUATION_FUNCTIONS"),
    "ALLOWED_SAFE_EQUATION_OPERATORS": (".safe_equations", "ALLOWED_SAFE_EQUATION_OPERATORS"),
    "EquationMeanFunction": (".gpytorch_gpr", "EquationMeanFunction"),
    "ExactGPRModel": (".gpytorch_gpr", "ExactGPRModel"),
    "ExactMultitaskGPRModel": (".multitask_gpr", "ExactMultitaskGPRModel"),
    "ExactSparseMultitaskGPRModel": (".sparse_multitask_gpr", "ExactSparseMultitaskGPRModel"),
    "FeatureSubsetKernel": (".kernels", "FeatureSubsetKernel"),
    "GPyTorchGPRResult": (".gpytorch_gpr", "GPyTorchGPRResult"),
    "GPyTorchPrediction": (".gpytorch_gpr", "GPyTorchPrediction"),
    "HeteroscedasticGPRPrediction": (".heteroscedastic_gpr", "HeteroscedasticGPRPrediction"),
    "HeteroscedasticGPRResult": (".heteroscedastic_gpr", "HeteroscedasticGPRResult"),
    "AugmentedTrainingData": (".physics_constraints", "AugmentedTrainingData"),
    "BayesianOptimizationResult": (".bayesian_optimization", "BayesianOptimizationResult"),
    "BOCampaignState": (".experiment_logging", "BOCampaignState"),
    "BOBenchmarkComparison": (".bo_benchmarking", "BOBenchmarkComparison"),
    "BOBenchmarkResult": (".bo_benchmarking", "BOBenchmarkResult"),
    "BOBenchmarkStrategy": (".bo_benchmarking", "BOBenchmarkStrategy"),
    "BORecommendationAudit": (".bayesian_optimization", "BORecommendationAudit"),
    "BoTorchSurrogate": (".bayesian_optimization", "BoTorchSurrogate"),
    "CandidateConstraint": (".bayesian_optimization", "CandidateConstraint"),
    "CandidateDuplicatePolicy": (".bayesian_optimization", "CandidateDuplicatePolicy"),
    "CandidatePoolDiagnostics": (".candidate_generation", "CandidatePoolDiagnostics"),
    "CandidateTrustRegion": (".bayesian_optimization", "CandidateTrustRegion"),
    "CoKrigingGPRPrediction": (".multifidelity_gpr", "CoKrigingGPRPrediction"),
    "CoKrigingGPRRegressor": (".multifidelity_gpr", "CoKrigingGPRRegressor"),
    "CoKrigingGPRResult": (".multifidelity_gpr", "CoKrigingGPRResult"),
    "CoKrigingTrainTestValidationResult": (".validation", "CoKrigingTrainTestValidationResult"),
    "DerivativeConstrainedGPRPrediction": (".derivative_gpr", "DerivativeConstrainedGPRPrediction"),
    "DerivativeConstrainedGPRResult": (".derivative_gpr", "DerivativeConstrainedGPRResult"),
    "DerivativeObservationSet": (".derivative_gpr", "DerivativeObservationSet"),
    "IdentityTargetTransform": (".target_transforms", "IdentityTargetTransform"),
    "KnownLimitConstraint": (".physics_constraints", "KnownLimitConstraint"),
    "LogTargetTransform": (".target_transforms", "LogTargetTransform"),
    "MatGPRRegressor": (".estimators", "MatGPRRegressor"),
    "MissingValueReport": (".estimators", "MissingValueReport"),
    "MonotonicDerivativeConstraint": (".derivative_gpr", "MonotonicDerivativeConstraint"),
    "MonotonicTrendConstraint": (".physics_constraints", "MonotonicTrendConstraint"),
    "MultiFidelityGPRPrediction": (".multifidelity_gpr", "MultiFidelityGPRPrediction"),
    "MultiFidelityGPRRegressor": (".multifidelity_gpr", "MultiFidelityGPRRegressor"),
    "MultiFidelityObservationData": (".multifidelity_gpr", "MultiFidelityObservationData"),
    "MultiObjectiveBayesianOptimizationResult": (
        ".bayesian_optimization",
        "MultiObjectiveBayesianOptimizationResult",
    ),
    "MultiObjectiveBoTorchSurrogate": (".bayesian_optimization", "MultiObjectiveBoTorchSurrogate"),
    "MultitaskGPRRegressor": (".estimators", "MultitaskGPRRegressor"),
    "MultitaskGPyTorchPrediction": (".multitask_gpr", "MultitaskGPyTorchPrediction"),
    "MultitaskGPyTorchResult": (".multitask_gpr", "MultitaskGPyTorchResult"),
    "MultitaskTrainTestValidationResult": (".validation", "MultitaskTrainTestValidationResult"),
    "PhysicsInformedMean": (".gpytorch_gpr", "PhysicsInformedMean"),
    "PhysicsInformedGPRRegressor": (".estimators", "PhysicsInformedGPRRegressor"),
    "PhysicsResidualTransform": (".target_transforms", "PhysicsResidualTransform"),
    "PhysicsEquationTemplate": (".physics_equations", "PhysicsEquationTemplate"),
    "PhysicsFeatureSpec": (".physics_equations", "PhysicsFeatureSpec"),
    "PhysicsParameterSpec": (".physics_equations", "PhysicsParameterSpec"),
    "CompositionFingerprintResult": (".inorganic_fingerprints", "CompositionFingerprintResult"),
    "CompositionFeaturizer": (".featurizers", "CompositionFeaturizer"),
    "CrossValidationResult": (".validation", "CrossValidationResult"),
    "DEFAULT_RDKIT_DESCRIPTORS": (".organic_fingerprints", "DEFAULT_RDKIT_DESCRIPTORS"),
    "DEFAULT_MAGPIE_PROPERTIES": (".featurizers", "DEFAULT_MAGPIE_PROPERTIES"),
    "DEFAULT_MAGPIE_STATISTICS": (".featurizers", "DEFAULT_MAGPIE_STATISTICS"),
    "DEFAULT_STRUCTURE_FEATURES": (".structure_fingerprints", "DEFAULT_STRUCTURE_FEATURES"),
    "DeltaMultiFidelityGPRResult": (".multifidelity_gpr", "DeltaMultiFidelityGPRResult"),
    "ElementFractionKernel": (".kernels", "ElementFractionKernel"),
    "ExactTwoLevelCoKrigingGPRModel": (".multifidelity_gpr", "ExactTwoLevelCoKrigingGPRModel"),
    "FINGERPRINT_CACHE_SCHEMA_VERSION": (".fingerprint_cache", "FINGERPRINT_CACHE_SCHEMA_VERSION"),
    "FeatureNoiseModel": (".noise_models", "FeatureNoiseModel"),
    "LearningCurveResult": (".validation", "LearningCurveResult"),
    "MagpieCompositionFeaturizer": (".featurizers", "MagpieCompositionFeaturizer"),
    "R_GAS_CONSTANT_J_MOL_K": (".physics_equations", "R_GAS_CONSTANT_J_MOL_K"),
    "SAFE_EQUATION_SCHEMA_VERSION": (".safe_equations", "SAFE_EQUATION_SCHEMA_VERSION"),
    "PolymerSmilesFeaturizer": (".featurizers", "PolymerSmilesFeaturizer"),
    "ObservationNoiseProfile": (".noise_models", "ObservationNoiseProfile"),
    "OPTIONAL_DEPENDENCIES": (".optional_dependencies", "OPTIONAL_DEPENDENCIES"),
    "OptionalDependency": (".optional_dependencies", "OptionalDependency"),
    "ObjectiveSpec": (".multi_objective", "ObjectiveSpec"),
    "ReplicateNoiseModel": (".noise_models", "ReplicateNoiseModel"),
    "SmilesFingerprintResult": (".organic_fingerprints", "SmilesFingerprintResult"),
    "SmilesFeaturizer": (".featurizers", "SmilesFeaturizer"),
    "SourceNoiseModel": (".noise_models", "SourceNoiseModel"),
    "SparseMultitaskGPRRegressor": (".estimators", "SparseMultitaskGPRRegressor"),
    "SparseMultitaskGPyTorchResult": (".sparse_multitask_gpr", "SparseMultitaskGPyTorchResult"),
    "SparseMultitaskObservationData": (".sparse_multitask_gpr", "SparseMultitaskObservationData"),
    "SparseMultitaskTrainTestValidationResult": (
        ".validation",
        "SparseMultitaskTrainTestValidationResult",
    ),
    "StandardizedTargetTransform": (".target_transforms", "StandardizedTargetTransform"),
    "StructureFeatureKernel": (".kernels", "StructureFeatureKernel"),
    "StructureFeaturizer": (".featurizers", "StructureFeaturizer"),
    "StructureFingerprintResult": (".structure_fingerprints", "StructureFingerprintResult"),
    "SafeEquationConstant": (".safe_equations", "SafeEquationConstant"),
    "SafeEquationEvaluationResult": (".safe_equations", "SafeEquationEvaluationResult"),
    "SafeEquationMeanFunction": (".safe_equations", "SafeEquationMeanFunction"),
    "SafeEquationMeanPreview": (".safe_equations", "SafeEquationMeanPreview"),
    "SafeEquationParameter": (".safe_equations", "SafeEquationParameter"),
    "SafeEquationSpec": (".safe_equations", "SafeEquationSpec"),
    "SafeEquationValidationIssue": (".safe_equations", "SafeEquationValidationIssue"),
    "SafeEquationValidationResult": (".safe_equations", "SafeEquationValidationResult"),
    "SafeEquationVariable": (".safe_equations", "SafeEquationVariable"),
    "TanimotoKernel": (".kernels", "TanimotoKernel"),
    "TargetTransformSpec": (".target_transforms", "TargetTransformSpec"),
    "TrainTestValidationResult": (".validation", "TrainTestValidationResult"),
    "VirtualObservationSet": (".physics_constraints", "VirtualObservationSet"),
    "append_composition_fingerprints": (
        ".inorganic_fingerprints",
        "append_composition_fingerprints",
    ),
    "append_element_fractions": (".inorganic_fingerprints", "append_element_fractions"),
    "append_magpie_composition_features": (".featurizers", "append_magpie_composition_features"),
    "append_smiles_features": (".organic_fingerprints", "append_smiles_features"),
    "append_structure_fingerprints": (".structure_fingerprints", "append_structure_fingerprints"),
    "append_closed_loop_records": (".experiment_logging", "append_closed_loop_records"),
    "append_virtual_observations": (".physics_constraints", "append_virtual_observations"),
    "arrhenius_linear_growth_equation": (".physics_equations", "arrhenius_linear_growth_equation"),
    "arrhenius_rate_equation": (".physics_equations", "arrhenius_rate_equation"),
    "arrhenius_sqrt_time_equation": (".physics_equations", "arrhenius_sqrt_time_equation"),
    "available_physics_equation_templates": (
        ".physics_equations",
        "available_physics_equation_templates",
    ),
    "available_target_transform_specs": (".target_transforms", "available_target_transform_specs"),
    "apply_candidate_constraints": (".bayesian_optimization", "apply_candidate_constraints"),
    "apply_candidate_duplicate_policy": (
        ".bayesian_optimization",
        "apply_candidate_duplicate_policy",
    ),
    "apply_candidate_trust_region": (".bayesian_optimization", "apply_candidate_trust_region"),
    "BoundedTargetTransform": (".target_transforms", "BoundedTargetTransform"),
    "build_additive_kernel": (".kernels", "build_additive_kernel"),
    "build_cartesian_candidate_grid": (".candidate_generation", "build_cartesian_candidate_grid"),
    "build_composition_candidate_grid": (
        ".candidate_generation",
        "build_composition_candidate_grid",
    ),
    "build_element_fraction_gpr_kernel": (".kernels", "build_element_fraction_gpr_kernel"),
    "build_product_kernel": (".kernels", "build_product_kernel"),
    "build_preprocessor": (".preprocessing", "build_preprocessor"),
    "build_safe_equation_mean_function": (".safe_equations", "build_safe_equation_mean_function"),
    "build_scaler": (".preprocessing", "build_scaler"),
    "build_sklearn_gpr_grid_search": (".sklearn_gpr", "build_sklearn_gpr_grid_search"),
    "build_sklearn_gpr_kernel": (".sklearn_gpr", "build_sklearn_gpr_kernel"),
    "build_sklearn_gpr_model": (".sklearn_gpr", "build_sklearn_gpr_model"),
    "build_structure_gpr_kernel": (".kernels", "build_structure_gpr_kernel"),
    "build_tanimoto_gpr_kernel": (".kernels", "build_tanimoto_gpr_kernel"),
    "canonicalize_molecule_smiles": (".organic_fingerprints", "canonicalize_molecule_smiles"),
    "canonicalize_polymer_smiles": (".organic_fingerprints", "canonicalize_polymer_smiles"),
    "calibration_curve": (".uncertainty", "calibration_curve"),
    "clean_formula": (".inorganic_fingerprints", "clean_formula"),
    "combine_virtual_observations": (".physics_constraints", "combine_virtual_observations"),
    "combine_derivative_observations": (".derivative_gpr", "combine_derivative_observations"),
    "combine_noise_profiles": (".noise_models", "combine_noise_profiles"),
    "compare_bo_strategies": (".bo_benchmarking", "compare_bo_strategies"),
    "composition_fingerprint": (".inorganic_fingerprints", "composition_fingerprint"),
    "constant_noise_profile": (".noise_models", "constant_noise_profile"),
    "cokriging_learning_curve": (".validation", "cokriging_learning_curve"),
    "cross_validate_regressor": (".validation", "cross_validate_regressor"),
    "default_element_symbols": (".inorganic_fingerprints", "default_element_symbols"),
    "describe_physics_equation_template": (
        ".physics_equations",
        "describe_physics_equation_template",
    ),
    "describe_target_transform_spec": (".target_transforms", "describe_target_transform_spec"),
    "decompose_multifidelity_prediction": (".reporting", "decompose_multifidelity_prediction"),
    "drop_columns_by_missing_fraction": (".data_cleaning", "drop_columns_by_missing_fraction"),
    "drop_duplicate_rows": (".data_cleaning", "drop_duplicate_rows"),
    "element_fraction_fingerprint": (".inorganic_fingerprints", "element_fraction_fingerprint"),
    "evaluate_cokriging_train_test_split": (".validation", "evaluate_cokriging_train_test_split"),
    "evaluate_multitask_train_test_split": (".validation", "evaluate_multitask_train_test_split"),
    "evaluate_sparse_multitask_train_test_split": (
        ".validation",
        "evaluate_sparse_multitask_train_test_split",
    ),
    "evaluate_train_test_split": (".validation", "evaluate_train_test_split"),
    "evaluate_safe_equation_numpy": (".safe_equations", "evaluate_safe_equation_numpy"),
    "evaluate_safe_equation_torch": (".safe_equations", "evaluate_safe_equation_torch"),
    "exclude_existing_candidates": (".candidate_generation", "exclude_existing_candidates"),
    "featurize_compositions": (".inorganic_fingerprints", "featurize_compositions"),
    "featurize_element_fractions": (".inorganic_fingerprints", "featurize_element_fractions"),
    "featurize_magpie_compositions": (".featurizers", "featurize_magpie_compositions"),
    "featurize_smiles": (".organic_fingerprints", "featurize_smiles"),
    "featurize_structures": (".structure_fingerprints", "featurize_structures"),
    "filter_iqr_outliers": (".data_cleaning", "filter_iqr_outliers"),
    "fit_botorch_surrogate": (".bayesian_optimization", "fit_botorch_surrogate"),
    "fit_cokriging_gpr": (".multifidelity_gpr", "fit_cokriging_gpr"),
    "fit_multi_objective_botorch_surrogate": (
        ".bayesian_optimization",
        "fit_multi_objective_botorch_surrogate",
    ),
    "fingerprint_smiles": (".organic_fingerprints", "fingerprint_smiles"),
    "fingerprint_cache_key": (".fingerprint_cache", "fingerprint_cache_key"),
    "fit_derivative_constrained_gpr": (".derivative_gpr", "fit_derivative_constrained_gpr"),
    "fit_delta_multifidelity_gpr": (".multifidelity_gpr", "fit_delta_multifidelity_gpr"),
    "fit_gpytorch_gpr": (".gpytorch_gpr", "fit_gpytorch_gpr"),
    "fit_heteroscedastic_gpr": (".heteroscedastic_gpr", "fit_heteroscedastic_gpr"),
    "fit_multitask_gpytorch_gpr": (".multitask_gpr", "fit_multitask_gpytorch_gpr"),
    "fit_pca": (".pca", "fit_pca"),
    "fit_sparse_multitask_gpytorch_gpr": (
        ".sparse_multitask_gpr",
        "fit_sparse_multitask_gpytorch_gpr",
    ),
    "free_volume_exponential_equation": (".physics_equations", "free_volume_exponential_equation"),
    "gaussian_nlpd": (".uncertainty", "gaussian_nlpd"),
    "get_physics_equation_template": (".physics_equations", "get_physics_equation_template"),
    "get_target_transform_spec": (".target_transforms", "get_target_transform_spec"),
    "hall_petch_equation": (".physics_equations", "hall_petch_equation"),
    "linear_parabolic_growth_equation": (".physics_equations", "linear_parabolic_growth_equation"),
    "linear_growth_equation": (".physics_equations", "linear_growth_equation"),
    "identify_feature_types": (".preprocessing", "identify_feature_types"),
    "impute_missing_values": (".data_cleaning", "impute_missing_values"),
    "interval_coverage": (".uncertainty", "interval_coverage"),
    "infer_next_bo_iteration": (".experiment_logging", "infer_next_bo_iteration"),
    "initialize_safe_equation_torch_parameters": (
        ".safe_equations",
        "initialize_safe_equation_torch_parameters",
    ),
    "is_optional_dependency_available": (
        ".optional_dependencies",
        "is_optional_dependency_available",
    ),
    "json_safe_diagnostics": (".uncertainty", "json_safe_diagnostics"),
    "json_safe_metrics": (".metrics", "json_safe_metrics"),
    "json_safe_regression_metrics": (".metrics", "json_safe_regression_metrics"),
    "json_safe_train_test_regression_metrics": (
        ".metrics",
        "json_safe_train_test_regression_metrics",
    ),
    "json_safe_uncertainty_diagnostics": (".uncertainty", "json_safe_uncertainty_diagnostics"),
    "load_artifact": (".io_utils", "load_artifact"),
    "load_closed_loop_log": (".experiment_logging", "load_closed_loop_log"),
    "list_optional_dependencies": (".optional_dependencies", "list_optional_dependencies"),
    "list_target_transform_specs": (".target_transforms", "list_target_transform_specs"),
    "log_bo_recommendations": (".experiment_logging", "log_bo_recommendations"),
    "log_experiment_result": (".io_utils", "log_experiment_result"),
    "log_observations": (".experiment_logging", "log_observations"),
    "log_selected_experiments": (".experiment_logging", "log_selected_experiments"),
    "list_physics_equation_templates": (".physics_equations", "list_physics_equation_templates"),
    "learning_curve": (".validation", "learning_curve"),
    "multifidelity_learning_curve": (".validation", "multifidelity_learning_curve"),
    "make_materials_target_transform": (".target_transforms", "make_materials_target_transform"),
    "make_target_transform": (".target_transforms", "make_target_transform"),
    "normalize_column_names": (".data_cleaning", "normalize_column_names"),
    "observation_noise_variance": (".bayesian_optimization", "observation_noise_variance"),
    "pairwise_composition_distance": (".kernels", "pairwise_composition_distance"),
    "pairwise_structure_distance": (".kernels", "pairwise_structure_distance"),
    "pairwise_tanimoto_similarity": (".kernels", "pairwise_tanimoto_similarity"),
    "pareto_front_mask": (".multi_objective", "pareto_front_mask"),
    "plot_bo_benchmark_trace": (".visualization", "plot_bo_benchmark_trace"),
    "plot_bo_campaign_progress": (".visualization", "plot_bo_campaign_progress"),
    "plot_bo_regret_trace": (".visualization", "plot_bo_regret_trace"),
    "plot_correlation_matrix": (".visualization", "plot_correlation_matrix"),
    "plot_distribution": (".visualization", "plot_distribution"),
    "plot_learning_curve": (".visualization", "plot_learning_curve"),
    "plot_parity": (".visualization", "plot_parity"),
    "plot_pca_scores": (".visualization", "plot_pca_scores"),
    "plot_pca_scree": (".visualization", "plot_pca_scree"),
    "plot_uncertainty_calibration": (".visualization", "plot_uncertainty_calibration"),
    "plot_uncertainty_vs_error": (".visualization", "plot_uncertainty_vs_error"),
    "prediction_interval_bounds": (".uncertainty", "prediction_interval_bounds"),
    "preview_safe_equation_mean": (".safe_equations", "preview_safe_equation_mean"),
    "predict_gpytorch_gpr": (".gpytorch_gpr", "predict_gpytorch_gpr"),
    "predict_multitask_gpytorch_gpr": (".multitask_gpr", "predict_multitask_gpytorch_gpr"),
    "predict_sparse_multitask_gpytorch_gpr": (
        ".sparse_multitask_gpr",
        "predict_sparse_multitask_gpytorch_gpr",
    ),
    "prepare_sparse_multitask_observations": (
        ".sparse_multitask_gpr",
        "prepare_sparse_multitask_observations",
    ),
    "prepare_multifidelity_observations": (
        ".multifidelity_gpr",
        "prepare_multifidelity_observations",
    ),
    "power_law_equation": (".physics_equations", "power_law_equation"),
    "rank_discrete_candidates": (".bayesian_optimization", "rank_discrete_candidates"),
    "rank_multi_objective_discrete_candidates": (
        ".bayesian_optimization",
        "rank_multi_objective_discrete_candidates",
    ),
    "rank_multi_objective_candidates": (".multi_objective", "rank_multi_objective_candidates"),
    "regression_metrics": (".metrics", "regression_metrics"),
    "replace_missing_placeholders": (".data_cleaning", "replace_missing_placeholders"),
    "resume_bo_campaign": (".experiment_logging", "resume_bo_campaign"),
    "require_optional_dependency": (".optional_dependencies", "require_optional_dependency"),
    "rule_of_mixtures_equation": (".physics_equations", "rule_of_mixtures_equation"),
    "safe_equation_schema_snapshot": (".safe_equations", "safe_equation_schema_snapshot"),
    "search_physics_equation_templates": (
        ".physics_equations",
        "search_physics_equation_templates",
    ),
    "search_target_transform_specs": (".target_transforms", "search_target_transform_specs"),
    "save_artifact": (".io_utils", "save_artifact"),
    "scalarize_objectives": (".multi_objective", "scalarize_objectives"),
    "separate_features_target": (".data_splitting", "separate_features_target"),
    "select_diverse_batch": (".bayesian_optimization", "select_diverse_batch"),
    "select_sequential_multi_objective_batch": (
        ".bayesian_optimization",
        "select_sequential_multi_objective_batch",
    ),
    "select_pareto_front": (".multi_objective", "select_pareto_front"),
    "simulate_bo_strategy": (".bo_benchmarking", "simulate_bo_strategy"),
    "split_train_test": (".data_splitting", "split_train_test"),
    "split_candidate_features": (".candidate_generation", "split_candidate_features"),
    "standardized_residuals": (".uncertainty", "standardized_residuals"),
    "structure_feature_names": (".structure_fingerprints", "structure_feature_names"),
    "structure_fingerprint": (".structure_fingerprints", "structure_fingerprint"),
    "summarize_bo_benchmark": (".bo_benchmarking", "summarize_bo_benchmark"),
    "summarize_closed_loop_log": (".experiment_logging", "summarize_closed_loop_log"),
    "summarize_missingness": (".reporting", "summarize_missingness"),
    "summarize_multifidelity_components": (".reporting", "summarize_multifidelity_components"),
    "summarize_multitask_predictions": (".validation", "summarize_multitask_predictions"),
    "summarize_numeric_columns": (".reporting", "summarize_numeric_columns"),
    "summarize_physics_equation_templates": (
        ".physics_equations",
        "summarize_physics_equation_templates",
    ),
    "summarize_sparse_multitask_predictions": (
        ".validation",
        "summarize_sparse_multitask_predictions",
    ),
    "summarize_target_transform_specs": (".target_transforms", "summarize_target_transform_specs"),
    "suggest_multi_objective_next_experiments": (
        ".bayesian_optimization",
        "suggest_multi_objective_next_experiments",
    ),
    "suggest_next_experiments": (".bayesian_optimization", "suggest_next_experiments"),
    "summarize_bo_recommendation_audit": (
        ".bayesian_optimization",
        "summarize_bo_recommendation_audit",
    ),
    "summarize_candidate_category_coverage": (
        ".candidate_generation",
        "summarize_candidate_category_coverage",
    ),
    "summarize_candidate_duplicates": (".candidate_generation", "summarize_candidate_duplicates"),
    "summarize_candidate_feature_coverage": (
        ".candidate_generation",
        "summarize_candidate_feature_coverage",
    ),
    "summarize_candidate_pool": (".candidate_generation", "summarize_candidate_pool"),
    "summarize_pca": (".pca", "summarize_pca"),
    "train_gpytorch_gpr": (".gpytorch_gpr", "train_gpytorch_gpr"),
    "train_multitask_gpytorch_gpr": (".multitask_gpr", "train_multitask_gpytorch_gpr"),
    "train_sparse_multitask_gpytorch_gpr": (
        ".sparse_multitask_gpr",
        "train_sparse_multitask_gpytorch_gpr",
    ),
    "train_test_regression_metrics": (".metrics", "train_test_regression_metrics"),
    "transform_pca": (".pca", "transform_pca"),
    "uncertainty_diagnostics": (".uncertainty", "uncertainty_diagnostics"),
    "uncertainty_error_correlation": (".uncertainty", "uncertainty_error_correlation"),
    "validate_safe_equation_spec": (".safe_equations", "validate_safe_equation_spec"),
}


def __getattr__(name: str) -> Any:
    """Load public exports on first access."""
    try:
        module_name, attribute_name = _LAZY_IMPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc

    module = import_module(module_name, __name__)
    value = getattr(module, attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return stable package-level exports for interactive discovery."""
    return sorted({*globals(), *__all__})
